### ISSUE TITLE
Crash with Fishing Made Better

### ISSUE THREAD

**Issue by Cephelo** [Wicked7000/EntityPurger#1]
[crash-2022-09-28_09.57.29-server.txt](https://github.com/Wicked7000/EntityPurger/files/9666329/crash-2022-09-28_09.57.29-server.txt)
When a fishing rod from Fishing Made Better is cast into a body of water with fish in it (ex: rivers or oceans, not small lakes), the game crashes.  
Fishing Made Better v2.2.4 
Entity Purger v1.2.3
Forge 14.23.5.2860

**Comment by Wicked7000** [comment]
This is an extremely late reply, but this is now fixed in the latest update of the mod (There are some other changes such as whitelist is now allowlist and blacklist is blocklist)

Other than that you should be all good, let me know if you still encounter issues.
(Wiki here: https://github.com/Wicked7000/EntityPurger/wiki/EntityPurger-1.2.4)
